name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: composer install

      - name: Generate Application Key
        run: php artisan key:generate --ansi

      - name: Run Migrations
        run: php artisan migrate
